### PR TITLE
Migration forgot password, profile and change global body style backgroundColor at __document.js

### PR DESCRIPTION
**Pull request by argikurnia1**
Migration forgot password, profile and change global body style backgroundColor at __document.js

### CODE REVIEW

**Comment by DeanIsHere** [comment]
y

**Comment by RifqiAdhityatama** [comment]
ga bener ah gi

**Comment by DeanIsHere** [comment]
benerin lagi lah kerjaanya

**Comment by argikurnia1** [comment]
yang bener2 aje lu

**Pull request merged**
